### ISSUE TITLE
Cyrillic-based keyboards not selectable on Mac

### ISSUE THREAD

**Issue by rueter** [divvun/kbdgen#4]
On Mac 12.5.1, I have had Erzya (myv) and Moksha (mdf) keyboards as well as several Latin-based keyboards Apurinã (apu), Lushootseed (lut), Tenino (tqn), Võro (vro).
After restarting my mac today, 2022-12-08, I have been unable to select a Cyrillic-based keyboard (a) from the keyboard, (b) manually attempting to select the language from the drop-down menu.

Upon adding a Mac Russian keyboard, both Erzya and Moksha mysteriously disappeared.

The same issue affects the keyboards: Mansi (mns), Kildin Saami, Khanty (kca)

**Comment by Trondtr** [comment]
I can confirm the behaviour reported: Today I installed the Mansi (mns) cyrillic-based keyboard, with the same result: 

I installed the Mansi keyboard, and after restart the Divvun installer claims it to be installed, as excpected. The keyboard, however, is nowhere to be found  in the System menu for adding keyboards. DI lists the keyboard as installed ("No updates"), but to no avail. Latin-based keyboards (e.g. fao, rmn) work well, the problem seems to be the cyrillic-based one.

The issue is somewhat acute, since we work on mns this week, but it is of course a problem also genarally speaking.

**Comment by snomos** [comment]
Further confirmed by me using Mansi as a test case. @zoomix could you have someone look at this?

Details:
- macOS 13.3.1 (a)
- bundle properly installed as `/Library/Keyboard\ Layouts/no.uit.giella.keyboards.mns.keyboardlayout.mns.bundle` using Divvun Manager
- not listed or visible at all in System Preferences (**System Preferences > Keyboards > Input sources**)

**Comment by dylanhand** [comment]
Hi @snomos,

@SteffenErn and I will look into it. 

Can you please provide steps to reproduce?

We have installed the Mac version of Divvun Manager from: https://divvun.no/en/index.html.

Upon opening Divvun Manager, there appears to be no option to install Mansi (mns):

![CleanShot 2023-05-03 at 12 28 59@2x](https://user-images.githubusercontent.com/431529/235892489-f2ec4b62-816a-4afd-bbda-bd4b0c34ee98.png)
![CleanShot 2023-05-03 at 12 29 03@2x](https://user-images.githubusercontent.com/431529/235892525-e12f4abe-2cf9-4d96-b367-f2712220c76f.png)

**Comment by snomos** [comment]
@dylanhand @SteffenErn — sorry, I forgot one step: you need to switch to the nightly channel in the app settings. After that the **All repositories** view will show Mansi near the bottom (it is written in Cyrillic, and the Cyrillic entries are towards the bottom - the actual packages are written in Latin, so should be no problem finding it).

**Comment by dylanhand** [comment]
We found the issue.

This occurs when the `.keylayout` file contains a self-closing  tag, such as:
```xml
<actions />`
```

The `.keylayout` file can be found in `/Library/Keyboard\ Layouts/<your language>.bundle/Contents/Resources`

The problem doesn't occur if this tag is either omitted or re-written as:
```xml
<actions></actions>
```

Our current plan to fix is to fork https://github.com/bbqsrc/xmlem and add an option to disable self-closing tags.

**Comment by bbqsrc** [comment]
> Our current plan fix is to fork https://github.com/bbqsrc/xmlem and add an option to disable self-closing tags.

Feel free to make a pull request and i can publish the fixes on cargo.

**Comment by snomos** [comment]
Good catch! And a pull request will be a perfect solution 🙂

**Comment by Trondtr** [comment]
So, what next? I understand the pull request is now done.

From my perspective I would then like to have a working Mansi keyboard on PC (Mac and Windows), my coworkers are typing in hex codes. Does the code in keyboard-xxx (here: keyboard-mns) need any changes, and if so, what changes?

**Comment by dylanhand** [comment]
@bbqsrc the option to disable self-closing tags ended up causing other issues. MacOS being persnickety 😄 

The fix was instead to remove the `<actions \>` tag altogether if it contained no children when generating MacOS layouts.

@Trondtr changes to keyboard-xxx repos should not be required for this fix to work on MacOS. I'm not sure about Windows though - are you having issue there too? If so please create an issue with details.

Next step is to merge this and then have `kbdgen` re-generate MacOS layouts so they're available in the nightly channel. Hopefully the merge will trigger that. Still learning the build chain. Will merge (if no objections) and investigate how to deploy the layouts to nightly after lunch 😄

**Comment by snomos** [comment]
@dylanhand  Please do merge.

**Comment by snomos** [comment]
@dylanhand rebuild of the keyboards do not happen automatically yet (cross-repo build deps have been planned, but not yet implemented). I will trigger new builds of the most critical keyboards as soon as the fix is merged and `kbdgen` has been rebuilt.

**Comment by dylanhand** [comment]
@snomos thanks for the info. 

Just merged, so feel free to trigger new builds of the keyboards.

**Comment by rueter** [comment]
I was able to download and install Mns (Mansi) keyboard on my Mac M2 13.0.1
It seems to work fine in the command line, so I am happy.
The keyboards for mhr (Meadow & Eastern Mari), mrj (Hill Mari aka Western Mari), myv (Erzya), mdf (Moksha), kpv (Komi-Zyrian), yrk (Nenets), did not show up as possible keyboards to install after they had been downloaded using Divvun Manager. All keyboards were downloaded at the same time.

**Comment by snomos** [comment]
@rueter all the mentioned keyboards have now been rebuilt to fix the issue. They also have a new version number. They should be available in Divvun Manager as updates. 

For keyboards with a Sámi flag as menu item icon, it has been replaced with a best effort alternative. Feel free to suggest other flags or icons 😊

**Comment by rueter** [comment]
@snomos 
The Cyrillic keyboards presently working are: myv, mdf, kpv

The mrj (Hill Mari aka Western Mari) keyboard is only partial. It contains none of the extras required for mrj, so we will have to work on that.
The mhr (Eastern & Meadow Mari) keyboard does not appear on my Ventura as a selectable, even after down loading it.
The udm keyboard, has a Saami flag and is, in fact, a Latin letter content. More work for us;)

**Comment by snomos** [comment]
Thanks for the feedback, I will look into the various points. Further discussion should take place in new issues specific for the relevant keyboards, if needed.

This issue is now fixed, thanks for reporting it 😊
